const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const INTERNAL_ERROR = 500;
const BAD_GATEWAY = 502;
const RESPONSE_OK = 200;
const RESPONSE_OK_CREATED = 201;
const RESPONSE_OK_NO_CONTENT = 204;
const NOK_USER_CREDENTIALS = 401;
const FORBIDDEN = 403;

module.exports = {
  NOT_FOUND_ERROR,
  FORBIDDEN,
  BAD_REQUEST_ERROR,
  INTERNAL_ERROR,
  RESPONSE_OK,
  RESPONSE_OK_NO_CONTENT,
  RESPONSE_OK_CREATED,
  BAD_GATEWAY,
  NOK_USER_CREDENTIALS
};
